### ISSUE TITLE
Extensions don't add pins to boards

### ISSUE THREAD

**Issue by aweathe** [lapo-luchini/browser-pinry#5]
Great plugin! Love it. I just noticed that when I add a pin through the extensions (chrome or Firefox) that it will add the pin, it will create a new board if I request, but it will never add a pin to a board.

Replicating this:
1. Select image/page to bookmark and use the 'Add to Pinry' context menu.
2. Select an available board e.g My Board
3. Click Save

The pin will be created but it will not be in the selected board.

I note the api call has no reference to the board
```
172.17.0.1 - - [12/Feb/2022:00:38:07 +0000] "POST /api/v2/pins/ HTTP/1.1" 201 1004 "http://localhost/pin-creation/from-url?url=https%3A%2F%2Ftransportsafety.vic.gov.au%2F__data%2Fassets%2Fimage%2F0003%2F32952%2FPowerboat.jpg&referer=https%3A%2F%2Ftransportsafety.vic.gov.au%2Fmaritime-safety%2Frecreational-boating%2Fpowerboat&description=Powerboats%20%7C%20Transport%20Safety%20Victoria"
```

**Comment by lapo-luchini** [comment]
Hi! Thanks. The plugin does not show the interface, i's a wrapper around the official bookmarklet that's distributed in Pinry proper ([as you can see here](https://github.com/lapo-luchini/browser-pinry/blob/master/content/bookmarklet.js#L14)), so you should open an issue in the main project. But I see that [you already did](https://github.com/pinry/pinry/issues/319). 👍
