### ISSUE TITLE
Sort picture picker by resolution 

### ISSUE THREAD

**Issue by luclu** [lapo-luchini/browser-pinry#6]
It would be a great improvement to have the picture picker sort alle pictures from highest to lowest resolution
and/or
have the right-clicked picture on top if possible.

Thank you :)

**Comment by lapo-luchini** [comment]
Hi! This project is just a browser helper to call [Pinry official bookmarklet script](https://github.com/pinry/pinry/blob/master/pinry/static/js/bookmarklet.js), any feature change should then be done here.

Funny thing is: I have exactly such a change locally, but I forgot to upstream it so far. I'll try and do it.
